name: Deploy to Railway

on:
  push:
    branches:
      - main
    paths:
      - packages/twitch-sirenachan/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: packages/twitch-sirenachan

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: ${{env.working-directory}}/package-lock.json

      - name: Install packages
        working-directory: ${{env.working-directory}}
        run: npm ci

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
